version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bookstars_db
      POSTGRES_USER: bookstars_user
      POSTGRES_PASSWORD: bookstars_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookstars_user -d bookstars_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 bookstars.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-simple-key-for-development-only
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - DB_NAME=bookstars_db
      - DB_USER=bookstars_user
      - DB_PASSWORD=bookstars_password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
